name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build, push
        run: |
          false
          echo hoge
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/util_container:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/util_container:${{ github.sha }}
